# Generated by Django 5.1.2 on 2024-11-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetectorSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_date", models.DateTimeField(editable=False)),
                ("value", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="HumiditySensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_date", models.DateTimeField(editable=False)),
                ("value", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="LightSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_date", models.DateTimeField(editable=False)),
                ("value", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ProximitySensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_date", models.DateTimeField(editable=False)),
                ("value", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="TemperatureSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_date", models.DateTimeField(editable=False)),
                ("value", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="VibratorSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_date", models.DateTimeField(editable=False)),
                ("value", models.BooleanField()),
            ],
        ),
    ]
