# Generated by Django 5.1.2 on 2024-11-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetectSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_date", models.DateTimeField(editable=False)),
                ("value", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
