# Generated by Django 5.1.2 on 2024-11-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectorsensor',
            name='value',
            field=models.FloatField(),
        ),
    ]
