# Generated by Django 5.1.2 on 2024-11-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(editable=False)),
                ('value', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DetectorSensor',
        ),
        migrations.DeleteModel(
            name='HumiditySensor',
        ),
        migrations.DeleteModel(
            name='LightSensor',
        ),
        migrations.DeleteModel(
            name='ProximitySensor',
        ),
        migrations.DeleteModel(
            name='TemperatureSensor',
        ),
        migrations.DeleteModel(
            name='VibratorSensor',
        ),
    ]
